export enum ETypeTagConstant {
  Text ='text',
  HtmlRaw ='html-raw',
  H1 ='h1',
  H2 ='h2',
  H3 ='h3',
  H4 ='h4',
  H5 ='h5',
  H6 ='h6',
  FileImage = 'file-image',
  Table = 'table',
  RichText = 'rich-text',
  ExternalVideo = 'external-video',
  UnsupportedTag = 'unsupported-tag',
}
